def city_2_iata(nombre_ciudad):
    ciudad = nombre_ciudad.upper().replace("Á", "A").replace("É", "E").replace("Í", "I").replace("Ó", "O").replace("Ú", "U").replace("Ü", "U").replace("Ñ", "N")
    match ciudad:
        case "BAHIA BLANCA": return "BHI"
        case "BUENOS AIRES": return "AEP"
        case "AREA METROPOLITANA DE BUENOS AIRES": return "EPA"
        case "SAN CARLOS DE BARILOCHE": return "BRC"
        case "SAN FERNANDO DEL VALLE DE CATAMARCA": return "CTC"
        case "COMODORO RIVADAVIA": return "CRD"
        case "CORDOBA": return "COR"
        case "CORRIENTES": return "CNQ"
        case "EL CALAFATE": return "FTE"
        case "ESQUEL": return "EQS"
        case "FORMOSA": return "FMA"
        case "LA RIOJA": return "IRJ"
        case "MAR DEL PLATA": return "MDQ"
        case "MALARGUE": return "LGS"
        case "MENDOZA": return "MDZ"
        case "NEUQUEN": return "NQN"
        case "PARANA": return "PRA"
        case "POSADAS": return "PSS"
        case "PUERTO IGUAZU": return "IGR"
        case "PUERTO MADRYN": return "PMY"
        case "RECONQUISTA": return "RCQ"
        case "RESISTENCIA": return "RES"
        case "RIO GALLEGOS": return "RGL"
        case "RIO GRANDE": return "RGA"
        case "RIO CUARTO": return "RCU"
        case "ROSARIO": return "ROS"
        case "SALTA": return "SLA"
        case "SAN JUAN": return "UAQ"
        case "SAN LUIS": return "LUQ"
        case "SAN MARTIN DE LOS ANDES": return "CPC"
        case "SAN MIGUEL DE TUCUMAN": return "TUC"
        case "SAN RAFAEL": return "AFA"
        case "SAN SALVADOR DE JUJUY": return "JUJ"
        case "SANTA FE": return "SFN"
        case "SANTA ROSA": return "RSA"
        case "SANTIAGO DEL ESTERO": return "SDE"
        case "TERMAS DE RIO HONDO": return "RHD"
        case "TRELEW": return "REL"
        case "USHUAIA": return "USH"
        case "VIEDMA": return "VDM"
        case "VILLA GESELL": return "VLG"
        case "ARICA": return "ARI"
        case "IQUIQUE": return "IQQ"
        case "ANTOFAGASTA": return "ANF"
        case "CALAMA": return "CJC"
        case "CALDERA": return "CPO"
        case "LA SERENA": return "LSC"
        case "SANTIAGO": return "SCL"
        case "CONCEPCION": return "CCP"
        case "FREIRE": return "ZCO"
        case "MARIQUINA": return "ZAL"
        case "OSORNO": return "ZOS"
        case "PUERTO MONTT": return "PMC"
        case "CASTRO": return "MHC"
        case "BALMACEDA": return "BBA"
        case "PUERTO NATALES": return "PNT"
        case "PUNTA ARENAS": return "PUQ"
        case "ISLA DE PASCUA": return "IPC"
        case "SAN ANDRES": return "ADZ"
        case "ARMENIA": return "AXM"
        case "BARRANQUILLA": return "BAQ"
        case "BUCARAMANGA": return "BGA"
        case "BOGOTA": return "BOG"
        case "CALI": return "CLO"
        case "CARTAGENA": return "CTG"
        case "CUCUTA": return "CUC"
        case "MEDELLIN": return "EOH"
        case "IBAGUE": return "IBE"
        case "LETICIA": return "LET"
        case "RIONEGRO": return "MDE"
        case "MANIZALES": return "MZL"
        case "NEIVA": return "NVA"
        case "PEREIRA": return "PEI"
        case "PASTO": return "PSO"
        case "POPAYAN": return "PPN"
        case "SANTA MARTA": return "SMR"
        case "MONTERIA": return "MTR"
        case "MITU": return "MVP"
        case "RIOHACHA": return "RCH"
        case "CIUDAD REAL": return "CQM"
        case "ALICANTE": return "ALC"
        case "ALMERIA": return "LEI"
        case "BADAJOZ": return "BJZ"
        case "BARCELONA": return "BCN"
        case "BILBAO": return "BIO"
        case "BURGOS": return "RGS"
        case "CASTELLON": return "CDT"
        case "CORDOBA": return "ODB"
        case "SAN SEBASTIAN": return "EAS"
        case "GERONA": return "GRO"
        case "GRANADA": return "GRX"
        case "IBIZA": return "IBZ"
        case "JEREZ": return "XRY"
        case "LANZAROTE": return "ACE"
        case "GRAN CANARIA": return "LPA"
        case "LEON": return "LEN"
        case "MADRID": return "MAD"
        case "MALAGA": return "AGP"
        case "MELILLA": return "MLN"
        case "MENORCA": return "MAH"
        case "MURCIA": return "RMU"
        case "ASTURIAS": return "OVD"
        case "PALMA DE MALLORCA": return "PMI"
        case "PAMPLONA": return "PNA"
        case "REUS": return "REU"
        case "SALAMANCA": return "SLM"
        case "SANTANDER": return "SDR"
        case "LA PALMA": return "SPC"
        case "SEVILLA": return "SVQ"
        case "TENERIFE NORTE": return "TFN"
        case "LA CORUNA": return "LCG"
        case "TENERIFE SUR": return "TFS"
        case "VALENCIA": return "VLC"
        case "VALLADOLID": return "VLL"
        case "EL HIERRO": return "VDE"
        case "VIGO": return "VGO"
        case "VITORIA": return "VIT"
        case "ZARAGOZA": return "ZAZ"
        case "SANTIAGO DE COMPOSTELA": return "SCQ"
        case "TERUEL": return "TEV"
        case "FUERTEVENTURA": return "FUE"
        case "LOGRONO": return "RJL"
        case "BARCELONA (VENEZUELA)": return "BLA"
        case "BARINAS": return "BNS"
        case "BARQUISIMETO": return "BRM"
        case "CIUDAD BOLIVAR": return "CBL"
        case "CARACAS": return "CCS"
        case "CUMANA": return "CUM"
        case "EL VIGIA": return "VIG"
        case "LA FRIA": return "LFR"
        case "PUNTO FIJO": return "LSP"
        case "LOS ROQUES": return "LRV"
        case "MARACAIBO": return "MAR"
        case "MATURIN": return "MUN"
        case "MARACAY": return "MYC"
        case "PORLAMAR": return "PMV"
        case "PUERTO CABELLO": return "PBL"
        case "PUERTO AYACUCHO": return "PYH"
        case "PUERTO ORDAZ": return "PZO"
        case "SAN FERNANDO DE APURE": return "SFD"
        case "SAN TOME": return "SOM"
        # Puedes seguir agregando más según necesidad.
        case _: return "CIUDAD DESCONOCIDA"
